const cds = require('@sap/cds')
const puppeteer = require('puppeteer-core')
const path = require('path')

// Путь к Chrome — приоритет: переменная окружения, затем дефолтный путь для Windows
const CHROME_PATH = 
  process.env.PUPPETEER_EXECUTABLE_PATH ||
  'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'

// Генерация HTML‑отчёта из JSON‑статистики
function generateHTMLReport(stats) {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { 
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
      line-height: 1.6; 
      color: #333;
    }
    .header { 
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
      color: white; 
      padding: 30px; 
      text-align: center;
    }
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 20px;
      padding: 30px;
    }
    .stat-card {
      background: white;
      padding: 25px;
      border-radius: 12px;
      box-shadow: 0 4px 20px rgba(0,0,0,0.1);
      border-left: 5px solid #667eea;
    }
    .stat-number {
      font-size: 2.5em;
      font-weight: bold;
      color: #667eea;
      margin-bottom: 5px;
    }
    .top-customers {
      background: white;
      margin: 30px;
      padding: 25px;
      border-radius: 12px;
      box-shadow: 0 4px 20px rgba(0,0,0,0.1);
    }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #eee; }
    th { background: #f8f9fa; font-weight: 600; }
    .footer {
      background: #f8f9fa;
      padding: 20px;
      text-align: center;
      font-size: 0.9em;
      color: #666;
      margin-top: 40px;
    }
    @media print {
      .stats-grid { grid-template-columns: repeat(2, 1fr); }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>📊 User Statistics Report</h1>
    <p>Generated on ${new Date().toLocaleDateString()}</p>
  </div>

  <div class="stats-grid">
    <div class="stat-card">
      <div class="stat-number">${stats.totalUsers.toLocaleString()}</div>
      <div>Total Users</div>
    </div>
    <div class="stat-card">
      <div class="stat-number">${stats.activeUsers.toLocaleString()}</div>
      <div>Active Users</div>
    </div>
    <div class="stat-card">
      <div class="stat-number">${stats.totalOrders.toLocaleString()}</div>
      <div>Total Orders</div>
    </div>
    <div class="stat-card">
      <div class="stat-number">$${stats.avgOrderValue.toLocaleString()}</div>
      <div>Avg Order Value</div>
    </div>
    <div class="stat-card">
      <div class="stat-number">$${stats.totalLifetimeValue.toLocaleString()}</div>
      <div>Total LTV</div>
    </div>
    <div class="stat-card">
      <div class="stat-number">${stats.avgOrdersPerUser.toFixed(1)}</div>
      <div>Avg Orders/User</div>
    </div>
    <div class="stat-card">
      <div class="stat-number">$${stats.avgLifetimeValue.toLocaleString()}</div>
      <div>Avg LTV/User</div>
    </div>
    <div class="stat-card">
      <div class="stat-number">${stats.newUsers2024.toLocaleString()}</div>
      <div>New Users 2024</div>
    </div>
  </div>

  <div class="top-customers">
    <h3>🏆 Top 5 Customers by LTV</h3>
    <table>
      <thead>
        <tr>
          <th>User ID</th>
          <th>Lifetime Value</th>
        </tr>
      </thead>
      <tbody>
        ${stats.topCustomers.map(customer => `
          <tr>
            <td>#${customer.userId}</td>
            <td>$${customer.lifetimeValue.toLocaleString()}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  </div>

  <div class="footer">
    Generated by SAP CAP Application
  </div>
</body>
</html>
  `
}

// Puppeteer PDF generation с явным указанием Chrome
async function generatePDFBuffer(html) {
  const browser = await puppeteer.launch({
    executablePath: CHROME_PATH,
    headless: true,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-gpu',
      '--disable-software-rasterizer'
    ]
  })

  try {
    const page = await browser.newPage()
    
    await page.setContent(html, {
      waitUntil: 'networkidle0'
    })

    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '20mm',
        bottom: '20mm',
        left: '15mm',
        right: '15mm'
      }
    })

    return pdfBuffer
  } finally {
    await browser.close().catch(() => {})
  }
}

module.exports = cds.service.impl(async function() {
  const { UserReports } = this.entities

  this.on('generateUserStatsPDF', async req => {
    const stats = req.data.stats

    // Генерируем HTML из данных
    const html = generateHTMLReport(stats)

    // Создаём PDF
    const pdfBuffer = await generatePDFBuffer(html)

    // Возвращаем бинарный PDF

    req._.res.setHeader('Content-Type', 'application/pdf')
    req._.res.setHeader('Content-Disposition', 'inline; filename="user-stats.pdf"')

    return pdfBuffer
  })
})